{{ if .Values.certManager.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: webhook
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.global.apiserver.ips }}
    - from:
        {{- range $IP := .Values.global.apiserver.ips }}
        - ipBlock:
            cidr: {{ $IP }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 10250 ## admission, use api server loop
    {{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
    {{- if and .Values.global.apiserver.port .Values.global.apiserver.ips }}
    - to:
        {{- range $IP := .Values.global.apiserver.ips }}
        - ipBlock:
            cidr: {{ $IP }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.global.apiserver.port }}
    {{- end }}
{{- end }}
