objectStorage: {}
  # gcs:
  #   keyfileData: |
  #     {}
  # s3:
  #   accessKey: "set-me"
  #   secretKey: "set-me"
user:
  grafanaPassword: somelongsecret
  prometheusPassword: somelongsecret
  alertmanagerPassword: somelongsecret
elasticsearch:
  adminPassword: somelongsecret
  fluentdPassword: somelongsecret
alerts:
  slack:
    apiUrl: somelongsecret
  opsGenie:
    apiKey: somelongsecret
dex:
  kubeloginClientSecret: somelongsecret
