{{ if .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-trivy-operator
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: trivy-operator
      app.kubernetes.io/name: trivy-operator
  policyTypes:
    - Egress
    - Ingress
  egress:
    {{- if and .Values.global.apiserver.ips .Values.global.apiserver.port }}
    - to:
        {{- range $IP := .Values.global.apiserver.ips }}
        - ipBlock:
            cidr: {{ $IP }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.global.apiserver.port }}
    {{- end }}
  ingress:
    - from: {{ toYaml .Values.global.prometheusSelector | nindent 8 }}
      ports:
        - port: 8080
          protocol: TCP
{{- end }}
