{{ if .Values.falco.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-falco
  namespace: falco
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: falco
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: falco
            app.kubernetes.io/name: falcosidekick
      ports:
        - port: 2801
    {{- if and .Values.global.apiserver.ips .Values.global.apiserver.port }}
    - to:
        {{- range $IP := .Values.global.apiserver.ips }}
      - ipBlock:
            cidr: {{ $IP }}
        {{- end }}
      ports:
        - port: {{ .Values.global.apiserver.port }}
    {{- end }}
    {{- if and .Values.falco.plugins.ips .Values.falco.plugins.ports }}
    - to:
        {{- range $ip := .Values.falco.plugins.ips }}
        - ipBlock:
            cidr: {{ $ip }}
        {{- end }}
      ports:
        {{- range $port := .Values.falco.plugins.ports }}
        - protocol: TCP
          port: {{ $port }}
        {{- end }}
    {{- end }}
    - ports:
        - port: 53
          protocol: UDP
{{- end }}
