apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRzNxSjJLd2xUa2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1ETXhORFF5TURGYUZ3MHpOVEV4TURFeE5EUTNNREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNtcDdpWENMcnVuT3hrVm54ZFZUZUQzcmpzcCtCVmtxYmVQcG9sVVZxMEh6U2ZKVVIxUzN2Y004aGQKS1VzN3kzbmdwR1lJb3lFb2tVcnV6K3FkNFFJZGxrVW5aQ2F3azNpZzlOMUY1QlRrQnNCQzI2aTBDbDkxSWtyMgp1Q0ZNR1F1VDh6NWcrWEt3SUNEMFRUSFJONDJ4RklrZjUyRUc1M3I2Ym5ieXp2ZUxYL01aRU8rSDErQ2pmelVJCkV4VTNIVFpSS2JhLzdFaHlPVjJTcWIwV0kwUW5jUVRkazFuWWVCS1B2TmJBZHhWK2Y5S1Y1aE14YjJYcjRVaFMKYlBxUW5NL2dWZ2ZtaTBaSS9UaEZKVG9ubzk1T29kN2Jnc1dTWVZPclFxYjc3M2JldGJ5VmxJKytNZi9URkpEYQpValUzcVRQMTJXVEFjZHhPYkxQRTJDdHlwNkZIQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUdEliQVdBaVJVNWFZNHhCYjdoZHUrbEdFVjlUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnExcUFOcGVndApjTmRjZml3ZjlJeThEVURRTDh0ZEVVbm9pcFBOalZSOE9EdzVGRk1jZHpsenRjRmFNcmc3WVV5aThCTm9icHl2CmxaQ2VpdzY3ZlhMWnVSNEFuU1hqUzVteWJqRHk0U3ZDSldrRyt4Sm95TU9ybGFsUlRzb1lrSXJYbm1ZV3FSSEQKUXVtaEpQVHRRTlFGOVV3NFFpM1hUaHJFS0tmbis1Y2M2WUg3b3dnUUdTT2ZxV1drNm5OcFdFdUlJeEgrOWR1QgpFeTk1cUNzd2JnWFZ6N3VvWThKZXBhU09WT2c0elFTWE00cFkzV0dGSzQvVENkS3FtZGVna29OUGxMcVlMTlA5ClJwRGt6ektLUXJzS2gzSi9CNEk3QlRVS2c1OGt5YTNVa0pCbUpwTHdBUUpibTNYaFJPN2FZTnhXbmpEUEdpNW0KVHFsVFdVUnRIR3dLCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://kube.ops.haorui-elastx.dev-ck8s.com:6443
  name: haorui-elastx-sc
contexts:
- context:
    cluster: haorui-elastx-sc
    namespace: default
    user: admin@haorui-elastx-sc
  name: haorui-elastx-sc
current-context: haorui-elastx-sc
kind: Config
preferences: {}
users:
- name: admin@haorui-elastx-sc
  user:
