localIP: 169.254.20.10

# IP of the cluster DNS in kubernetes
clusterDNS: 10.43.0.10

# Local DNS dynamic resource allocation
resources:
  requests:
    cpu: 25m
    memory: 40Mi


# See docs for details about the config format and options:
# https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
customConfig: #|-
#  example.com:53 {
#      errors
#      cache 30
#      reload
#      loop
#      forward . 127.0.0.1:9005
#      }


serviceMonitor:
  metricRelabelings: []
