opensearch:
  s3:
    enabled: false
    accessKey:
    secretKey:
    secret:
  gcs:
    enabled: false
    keyfile:
    secret:
  azure:
    enabled: false
    account: 
    key:
    secret: 

  users:
    - username:
      password:
      cookie:
      secret:

  certificates:
    ca:
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages: []
      organization:
    admin:
      enabled: true
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages:
      - server auth
      - client auth
      organization:
      secret:
    transport:
      enabled: true
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages:
      - server auth
      - client auth
      organization:
      secret:
    http:
      enabled: true
      commonName: example.com
      duration: 21600h
      renewBefore: 360h
      keySize: 2048
      usages:
      - server auth
      - client auth
      organization:
      secret:
