{{- range $namespace, $services := .Values.constraints }}
{{- range $name, $value := $services }}
{{- if hasKey $value.allow "allowedCapabilities" }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPCapabilities
metadata:
  name: {{ printf "capabilities-%s" $name | trunc 63 }}
spec:
  match:
    {{- dict "namespace" $namespace "labels" $value.podSelectorLabels | include "podsecuritypolicies.renderMatchInclusion" | nindent 4 }}
  parameters:
    allowedCapabilities:
      {{- toYaml $value.allow.allowedCapabilities | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
