{{- range $namespace, $services := .Values.constraints }}
{{- range $name, $value := $services }}
{{- if hasKey $value.allow "allowedHostPaths" }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostFilesystem
metadata:
  name: {{ printf "host-paths-%s" $name | trunc 63 }}
spec:
  match:
    {{- dict "namespace" $namespace "labels" $value.podSelectorLabels | include "podsecuritypolicies.renderMatchInclusion" | nindent 4 }}
  parameters:
    allowedHostPaths:
      {{- toYaml $value.allow.allowedHostPaths | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
