{{- range $namespace, $services := .Values.constraints }}
{{- range $name, $value := $services }}
{{- if pick $value.allow "runAsUser" "runAsGroup" "supplementalGroups" "fsGroup" }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: {{ printf "users-%s" $name | trunc 63 }}
spec:
  match:
    {{- dict "namespace" $namespace "labels" $value.podSelectorLabels | include "podsecuritypolicies.renderMatchInclusion" | nindent 4 }}
  parameters:
    runAsUser:
      {{- with $value.allow.runAsUser }}
      {{- toYaml . | nindent 6 }}
      {{- else }}
      rule: MustRunAsNonRoot
      {{- end }}
    runAsGroup:
      {{- with $value.allow.runAsGroup }}
      {{- toYaml . | nindent 6 }}
      {{- else }}
      rule: MustRunAs
      ranges:
      - max: 65535
        min: 1
      {{- end }}
    supplementalGroups:
      {{- with $value.allow.supplementalGroups }}
      {{- toYaml . | nindent 6 }}
      {{- else }}
      rule: MustRunAs
      ranges:
      - max: 65535
        min: 1
      {{- end }}
    fsGroup:
      {{- with $value.allow.fsGroup }}
      {{- toYaml . | nindent 6 }}
      {{- else }}
      rule: MustRunAs
      ranges:
      - max: 65535
        min: 1
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
