apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      containers:
        - name: run
          image: ghcr.io/elastisys/curl-jq:1.0.0
          command: ['/bin/bash', '/scripts/init-harbor.sh']
          securityContext:
            runAsUser: 10000
          env:
            - name: ENDPOINT
              value: {{ .Values.endpoint }}
            - name: OIDC_VERIFY_CERT
              value: {{ .Values.oidc.verifyCert | quote }}
            - name: OIDC_SCOPE
              value: {{ .Values.oidc.scope }}
            - name: OIDC_ADMIN_GROUP_NAME
              value: {{ .Values.oidc.adminGroupName }}
            - name: OIDC_GROUP_CLAIM_NAME
              value: {{ .Values.oidc.groupClaimName }}
            - name: OIDC_ENDPOINT
              value: {{ .Values.oidc.endpoint }}
            - name: GC_ENABLED
              value: {{ .Values.gc.enabled | quote }}
            - name: GC_SCHEDULE
              value: {{ .Values.gc.schedule | quote }}
            - name: GC_FORCE_CONFIGURE
              value: {{ .Values.gc.forceConfigure | quote }}
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-init-secret
                  key: harbor-password
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-init-secret
                  key: oidc-client-secret
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: {{ .Release.Name }}-cm
