helmDefaults:
  createNamespace: false
  skipDeps: true
  timeout: 1800

environments:
  local_cluster:
    values:
      - ck8sManagementCluster: { enabled: false }
      - ck8sWorkloadCluster: { enabled: false }
      - ck8sLocalCluster: { enabled: true }
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/sc-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/sc-config.yaml
    secrets:
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml

  service_cluster:
    values:
      - ck8sManagementCluster: { enabled: true }
      - ck8sWorkloadCluster: { enabled: false }
      - ck8sLocalCluster: { enabled: false }
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/sc-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/sc-config.yaml
    secrets:
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml
  workload_cluster:
    values:
      - ck8sManagementCluster: { enabled: false }
      - ck8sWorkloadCluster: { enabled: true }
      - ck8sLocalCluster: { enabled: false }
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/wc-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/wc-config.yaml
    secrets:
      - {{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml

templates:
  networkpolicies:
    chart: helmfile/charts/networkpolicy/generator
    version: 0.1.0
    name: networkpolicy
    labels:
      policy: netpol

  podsecuritypolicies:
    disableValidationOnInstall: true
    chart: helmfile/charts/gatekeeper/podsecuritypolicies
    version: 0.1.0
    name: podsecuritypolicy
    labels:
      policy: psp
    needs:
      - gatekeeper-system/gatekeeper-templates # creates gatekeeper/constraints and gatekeeper/mutations
