{{- if and .Values.defaultRules.create .Values.defaultRules.rules.hnc }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "prometheus-alerts.fullname" .) "hnc" | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ template "prometheus-alerts.name" . }}
    {{- include "prometheus-alerts.labels" . | nindent 4 }}
    {{- with .Values.defaultRules.alertLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.defaultRules.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
    {{- .Files.Get "files/hnc.yaml" | nindent 4 }}
{{- end }}
