apiVersion: v1
kind: Secret
metadata:
  name: harbor-backup-secret
type: Opaque
stringData:
  aws-access-key-id: "{{ .Values.s3.accessKey }}"
  aws-secret-access-key: "{{ .Values.s3.secretKey }}"
  db-password: "{{ .Values.dbPassword }}"
