{{ if .Values.opensearch.enabled }}
{{- if .Values.opensearch.client.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-opensearch-client
  namespace: opensearch-system
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: opensearch-client
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-master
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-data
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-client
      ports:
        - port: 9300
    # Allow api port from ingress-ngix
    - from:
      {{- if and .Values.global.ingressUsingHostNetwork .Values.global.scNodes.ips }}
        {{- range $ip := .Values.global.scNodes.ips }}
        - ipBlock:
            cidr: {{ $ip }}
        {{- end }}
      {{- else }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
              app.kubernetes.io/instance: ingress-nginx
      {{- end }}
      ports:
        - port: 9200
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-master
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-data
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-client
      ports:
        - port: 9300
    {{- if and .Values.global.objectStorage.ips .Values.global.objectStorage.ports }}
    - to:
        {{- range $ip := .Values.global.objectStorage.ips }}
        - ipBlock:
            cidr: {{ $ip }}
        {{- end }}
      ports:
        {{- range $port := .Values.global.objectStorage.ports }}
        - protocol: TCP
          port: {{ $port }}
        {{- end }}
    {{- end }}
    {{- if and .Values.opensearch.plugins.ips .Values.opensearch.plugins.ports }}
    - to:
        {{- range $ip := .Values.opensearch.plugins.ips }}
        - ipBlock:
            cidr: {{ $ip }}
        {{- end }}
      ports:
        {{- range $port := .Values.opensearch.plugins.ports }}
        - protocol: TCP
          port: {{ $port }}
        {{- end }}
    {{- end }}
    - ports:
        - port: 53
          protocol: UDP
{{- end }}
{{ end }}
