{{ if .Values.opensearch.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-opensearch-prometheus-exporter
  namespace: opensearch-system
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: prometheus-elasticsearch-exporter
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kube-prometheus-stack-prometheus
              app.kubernetes.io/name: prometheus
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 9108
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: opensearch-master
      ports:
        - port: 9200
    - ports:
        - port: 53
          protocol: UDP
{{ end }}
