# Based on https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
{{- if and .Values.defaultRules.create .Values.defaultRules.rules.rookMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "prometheus-alerts.fullname" .) "rook-records" | trunc 63 | trimSuffix "-" }}
  namespace: "rook-ceph"
  labels:
    app: {{ template "prometheus-alerts.name" . }}
{{ include "prometheus-alerts.labels" . | indent 4 }}
{{- if .Values.defaultRules.recordLabels }}
{{ toYaml .Values.defaultRules.recordLabels | indent 4 }}
{{- end }}
{{- if .Values.defaultRules.annotations }}
  annotations:
{{ toYaml .Values.defaultRules.annotations | indent 4 }}
{{- end }}
spec:
  # The rules contain templates for prometheus, which breaks helm if trying
  # to render them. We have to either escape them or (as we do here) include
  # them without going through the template rendering.
  {{- .Files.Get "files/rook-records.yaml" | nindent 2}}
{{- end }}
