objectStorage: {}
grafana:
    password: somelongsecret
    clientSecret: somelongsecret
harbor:
    password: somelongsecret
    databasePassword: somelongsecret
    clientSecret: somelongsecret
    xsrf: somelongsecretandsomelongsecrets
    coreSecret: somelongsecret
    jobserviceSecret: somelongsecret
    registrySecret: somelongsecret
opensearch:
    adminPassword: somelongsecret
    adminHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
    clientSecret: somelongsecret
    configurerPassword: somelongsecret
    configurerHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
    dashboardsPassword: somelongsecret
    dashboardsHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
    dashboardsCookieEncKey: abcdefghijklmnopqrstuvabcdefghij
    fluentdPassword: somelongsecret
    curatorPassword: somelongsecret
    snapshotterPassword: somelongsecret
    metricsExporterPassword: somelongsecret
kubeapiMetricsPassword: somelongsecret
alerts:
    slack:
        apiUrl: somelongsecret
    opsGenie:
        apiKey: somelongsecret
dex:
    staticPassword: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
    kubeloginClientSecret: somelongsecret
    connectors: []
    additionalStaticClients: []
user:
    grafanaPassword: somelongsecret
    alertmanagerPassword: somelongsecret
prometheus:
    remoteWrite:
        password: somelongsecret
