nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6443
  externalName: ""

ingress:
  enabled: false
  clusterDomain: ""
  username: ""
  password: ""
  extraAnnotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
