{{- if .Values.kured.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "np.labels" . | nindent 4 }}
  name: allow-kured
  namespace: kured
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kured
  ingress:
    - from: {{ toYaml .Values.global.prometheusSelector | nindent 8 }}
      ports:
        - port: 8080
  egress:
    - ports:
        - port: 53
          protocol: UDP
    {{- if and .Values.global.apiserver.ips .Values.global.apiserver.port }}
    - to:
        {{- range .Values.global.apiserver.ips }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - port: {{ .Values.global.apiserver.port }}
    {{- end }}
    {{- if and .Values.kured.notificationSlack.enabled .Values.kured.notificationSlack.ips .Values.kured.notificationSlack.ports }}
    - to:
        {{- range .Values.kured.notificationSlack.ips }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.kured.notificationSlack.ports }}
        - port: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
