{{- if .Values.rcloneSync.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rclone-sync
  namespace: kube-system
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: rclone-sync
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if and .Values.rcloneSync.objectStorage.ips .Values.rcloneSync.objectStorage.ports }}
    - to:
        {{- range .Values.rcloneSync.objectStorage.ips | uniq }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.rcloneSync.objectStorage.ports | uniq }}
        - port: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
