{{- $namespaces := keys .Values.constraints | sortAlpha }}
{{- $exceptions := list }}
{{- range $namespace, $services := .Values.constraints }}
{{- range $services }}
{{- if hasKey .allow "allowedUnsafeSysctls" }}
{{- $exceptions = append $exceptions .podSelectorLabels }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPForbiddenSysctls
metadata:
  name: {{ printf "sysctls-%s-restricted" .Release.Namespace | trunc 63 }}
spec:
  match:
    {{- dict "namespaces" $namespaces "exceptions" $exceptions | include "podsecuritypolicies.renderMatchExceptions" | nindent 4 }}
  parameters:
    allowedSysctls: []
    forbiddenSysctls:
      - "*"
