# Default values for openstack-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
openstackMonitoring:
  enabled: false
serviceMonitor:
  labels: {}
  namespace: ""
