# Changes made here will override the default values for both the service and workload cluster.
# See the default configuration under "defaults/" to see available and suggested options.
global:
  baseDomain: pipeline-elastx.dev-ck8s.com
  opsDomain: ops.pipeline-elastx.dev-ck8s.com
issuers:
  letsencrypt:
    prod:
      email: letsencrypt@elastisys.com
    staging:
      email: letsencrypt@elastisys.com
clusterAdmin:
  users: []
  groups:
    - self-managed@elastisys.com
opa:
  imageRegistry:
    URL:
      - harbor.pipeline-elastx.dev-ck8s.com
      - quay.io/jetstack/cert-manager-acmesolver
  networkPolicies:
    enabled: false
kured:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: elastisys.io/node-type
      operator: Exists
      effect: NoSchedule
  notification:
    slack:
      enabled: false
      channel: kured-notification
networkPolicies:
  global:
    trivy:
      ips:
        - 0.0.0.0/0
    objectStorage:
      ips:
        - 0.0.0.0/0
      ports:
        - 443
    scIngress:
      ips:
        - 0.0.0.0/0
    wcIngress:
      ips:
        - 0.0.0.0/0
  coredns:
    enabled: false
    externalDns:
      ips:
        - 0.0.0.0/0
  kured:
    enabled: false
    notificationSlack:
      ips:
        - 0.0.0.0/0
  falco:
    enabled: false
    plugins:
      ips:
        - 0.0.0.0/0
  alertmanager:
    enabled: false
    alertReceivers:
      ips:
        - 0.0.0.0/0
  velero:
    enabled: false
  certManager:
    enabled: false
  ingressNginx:
    enabled: false
  externalDns:
    enabled: false
  gatekeeper:
    enabled: false
  kubeSystem:
    enabled: false
    openstack:
      enabled: false
  kyverno:
    enabled: false
  dnsAutoscaler:
    enabled: false
  opensearch:
    enabled: false
trivy:
  nodeCollector:
    tolerations:
      - key: elastisys.io/node-type
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
ingressNginx:
  controller:
    config:
      useProxyProtocol: false
    service:
      annotations:
        service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
        loadbalancer.openstack.org/proxy-protocol: "false"
