{{- if and .Values.kubeSystem.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "np.labels" . | nindent 4 }}
  name: allow-snapshot-controller
  namespace: kube-system
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app: snapshot-controller
  ingress: []
  egress:
    - ports:
        - port: 53
          protocol: UDP
    {{- if and .Values.global.apiserver.ips .Values.global.apiserver.port }}
    - to:
        {{- range .Values.global.apiserver.ips }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - port: {{ .Values.global.apiserver.port }}
    {{- end }}
{{- end }}
