networkPolicies:
  global:
    ingressMode: DirectRouting
    ingressDirectRoutingAllowlistPeers:
       - cidr: 0.0.0.0/0
ingressNginx:
  controller:
    service:
      enabled: true
      type: LoadBalancer
    useHostPort: false
