{{ if .Values.ingressNginx.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-nginx-webhook
  namespace: ingress-nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: admission-webhook
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
    {{- if and .Values.global.wcApiserver.ips .Values.global.wcApiserver.port }}
    - to:
        {{- range $IP := .Values.global.wcApiserver.ips }}
        - ipBlock:
            cidr: {{ $IP }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.global.wcApiserver.port }}
    {{- end }}
{{- end }}
