apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ck8sdash.fullname" . }}-secrets
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
type: Opaque
stringData:
  grafana-password: "{{ .Values.grafana.password }}"
  harbor-password: "{{ .Values.harbor.password }}"
  oidc-secret: "{{ .Values.oidc.secret }}"
