{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "ck8sdash.fullname" . }}
  labels:
{{ include "ck8sdash.labels" . | indent 4 }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: {{ .Values.ingress.issuer }}
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
    - {{ include "ck8sdash.fullname" . }}.{{ required "Cluster domain required" .Values.ingress.clusterDomain }}
    secretName: {{ include "ck8sdash.fullname" . }}-cert
  rules:
  - host: {{ include "ck8sdash.fullname" . }}.{{ required "Cluster domain required" .Values.ingress.clusterDomain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "ck8sdash.fullname" . }}
            servicePort: {{ .Values.service.port }}
{{- end -}}
