pgHostname: harbor-database
dbPassword: ""
retentionDays: 7
schedule: "0 0 * * *"
s3:
  enabled: false
  accessKey: ""
  secretKey: ""
  bucket: ""
  endpoint: ""
gcs:
  enabled: false
  keyfileData: ""
  bucket: ""
startingDeadlineSeconds: 200
ephemeralBackupStore:
  enabled: false
  storageSize: 10Gi
