{{- $namespaceSelectorLabels := .Values.mutations.namespaceSelectorLabels }}
{{- $namespaces := keys .Values.constraints | sortAlpha }}
{{- $exceptions := .Values.mutations.exceptions }}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: host-pid-restricted
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    {{- dict "namespaceSelectorLabels" $namespaceSelectorLabels "namespaces" $namespaces "exceptions" $exceptions | include "podsecuritypolicies.renderMatchExceptions" | nindent 4 }}
  location: "spec.hostPID"
  parameters:
    assign:
      value: false
    pathTests:
      - subPath: "spec.hostPID"
        condition: MustNotExist
