{{- if .Values.rookMonitor.enabled }}
# Based on https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-%s" (include "prometheus-alerts.fullname" .) "rook-ceph-mgr" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.rookMonitor.namespace }}
  labels:
    team: rook
{{ include "prometheus-alerts.labels" . | indent 4 }}
{{- if .Values.defaultRules.labels }}
{{ toYaml .Values.defaultRules.labels | indent 4 }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 5s
    # Add the correct cluster labels so we know what cluster this comes from.
    relabelings:
    {{- toYaml .Values.rookMonitor.relabelings | nindent 6 }}
{{- end }}
