endpoint: harbor-harbor-core/api/v2.0
#Should be overwritten with more secure password
password: "Harbor12345"

oidc:
  scope: "openid,email,profile,offline_access,groups"
  clientSecret: ""
  endpoint: ""
  verifyCert: true
  groupClaimName: groups
